version: '3.8'

services:
  app:
    build: .
    container_name: nginx_nodejs
    restart: always
    ports:
      - "80:80"  
      - "443:443"
    volumes:
      - ./app:/app  
    environment:
      NODE_ENV: production
